node.id=node1
default.hostname=127.0.0.1
server.port=5001
log.file.path=node1.log
neighbor.nodes=node2:5002,node3:5003
node.successor.id=node2
node.successor.port=5002
node.predecessor.id=node3
node.predecessor.port=5003
log.timezone=Europe/Bucharest